//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viettours.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class danhmuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public danhmuc()
        {
            this.tourNNs = new HashSet<tourNN>();
            this.tourNNs1 = new HashSet<tourNN>();
            this.tourTNs = new HashSet<tourTN>();
        }
        [Key]
        [StringLength(10)]
        [Required(ErrorMessage = "ID không được để trống")]
        [DisplayName("Mã danh mục")]
        public string id { get; set; }

        [StringLength(30)]
        [Required(ErrorMessage = "Tên danh mục không được để trống")]
        [RegularExpression("([a-z0-9A-Z_ãáàảạẽéèẻẹũúùủụõóòỏọĩíìỉịẫấầẩậễếềểệữứừửựỗốồổộỹýỳỷỵẵắằẳặỡớờởợâăêôươÃÁÀẢẠẼÉÈẺẸŨÚÙỦỤÕÓÒỎỌĨÍÌỈỊẪẤẦẨẬỄẾỀỂỆỮỨỪỬỰỖỐỒỔỘỸÝỲỶỴẴẮẰẲẶỠỚỜỞỢÂĂÊÔƯƠ, ().&\"'-–]+)", ErrorMessage = "Tên danh mục không đúng định dạng")]
        [DisplayName("Tên danh mục")]
        public string name { get; set; }

        [StringLength(50)]
        [Required(ErrorMessage = "Mô tả không được để trống")]
        [RegularExpression("([a-z0-9A-Z_ãáàảạẽéèẻẹũúùủụõóòỏọĩíìỉịẫấầẩậễếềểệữứừửựỗốồổộỹýỳỷỵẵắằẳặỡớờởợâăêôươÃÁÀẢẠẼÉÈẺẸŨÚÙỦỤÕÓÒỎỌĨÍÌỈỊẪẤẦẨẬỄẾỀỂỆỮỨỪỬỰỖỐỒỔỘỸÝỲỶỴẴẮẰẲẶỠỚỜỞỢÂĂÊÔƯƠ, ().&\"'-–]+)", ErrorMessage = "Mô tả không đúng định dạng")]
        [DisplayName("Mô tả")]
        public string mota { get; set; }

        public virtual danhmuccon danhmuccon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tourNN> tourNNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tourNN> tourNNs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tourTN> tourTNs { get; set; }
    }
}
