//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viettours.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class post
    {
        public int id { get; set; }
        [StringLength(100)]
        [Required(ErrorMessage = "Title không được để trống")]
        [RegularExpression("([a-z0-9A-Z_ãáàảạẽéèẻẹũúùủụõóòỏọĩíìỉịẫấầẩậễếềểệữứừửựỗốồổộỹýỳỷỵẵắằẳặỡớờởợâăêôươÃÁÀẢẠẼÉÈẺẸŨÚÙỦỤÕÓÒỎỌĨÍÌỈỊẪẤẦẨẬỄẾỀỂỆỮỨỪỬỰỖỐỒỔỘỸÝỲỶỴẴẮẰẲẶỠỚỜỞỢÂĂÊÔƯƠ, ().&\"'-–]+)", ErrorMessage = "Title không đúng định dạng")]
        [DisplayName("Tiêu đề")]
        public string title { get; set; }

        [StringLength(60)]
        [DisplayName("Ảnh")]
        public string anh { get; set; }


        [DisplayName("Loại")]
        public Nullable<int> loai { get; set; }

        [StringLength(50)]
        [RegularExpression("([a-z0-9A-Z_ãáàảạẽéèẻẹũúùủụõóòỏọĩíìỉịẫấầẩậễếềểệữứừửựỗốồổộỹýỳỷỵẵắằẳặỡớờởợâăêôươÃÁÀẢẠẼÉÈẺẸŨÚÙỦỤÕÓÒỎỌĨÍÌỈỊẪẤẦẨẬỄẾỀỂỆỮỨỪỬỰỖỐỒỔỘỸÝỲỶỴẴẮẰẲẶỠỚỜỞỢÂĂÊÔƯƠ, ().&\"'-–]+)", ErrorMessage = "Mô tả ngắn không đúng định dạng")]
        [DisplayName("Mô tả ngắn")]
        public string motangan { get; set; }

        [DisplayName("Mã danh mục")]
        public string id_danhmuc { get; set; }

        [DisplayName("Nội dung")]
        public string mota { get; set; }
    }
}
