//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viettours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tourTN
    {
        public int id { get; set; }
        public string id_danhmuc { get; set; }
    
        public virtual danhmuc danhmuc { get; set; }
        public virtual tour tour { get; set; }
    }
}
